### ISSUE TITLE
pitest EOFException when used with SpringbootTest +WireMock

### ISSUE THREAD

**Issue by shorttough** [jopt-simple/jopt-simple#154]
Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : Red Hat, Inc.
Version : 25.322-b06
Uptime : 223716
Input -> 
 1 : -Dfile.encoding=US-ASCII
 2 : -Duser.country=US
 3 : -Duser.language=en
 4 : -Duser.variant
 5 : -XX:+UnlockExperimentalVMOptions
 6 : -XX:+UseCGroupMemoryLimitForHeap
 7 : -XX:MaxRAMFraction=4
 8 : -XX:MaxMetaspaceSize=256m
BootClassPathSupported : true
	at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
	at org.pitest.util.SafeDataInputStream.readByte(SafeDataInputStream.java:78)
	at org.pitest.util.SocketReadingCallable.receiveResults(SocketReadingCallable.java:54)
	at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:34)
	at org.pitest.util.SocketReadingCallable.call(SocketReadingCallable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 1 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.pitest.util.SafeDataInputStream.readByte(SafeDataInputStream.java:76)
	... 5 more
4:26:58 AM PIT >> WARNING : Minion exited abnormally due to RUN_ERROR

**Comment by pholser** [comment]
?
